### PR TITLE
New Version 2.0

### PR DESCRIPTION
**Pull request by dakhama-mehdi**
Hi, I rewrote a new version ,faster modern source code compatible with all language versions. with to issue generat one page or more page hosted on server web like IIS.
i'm using PSWritHTML module, this new version allows to filter by multiple parameters like OU path, logondate, enabled .... 

on big company with more 10K objects the first projects taked many times more that 1 hours, on it's under 3 minutes for 50K objects and very secure.

I'm added the script for the moment in my github to share result,

### CODE REVIEW

**Comment by dakhama-mehdi** [comment]
here is the new code sharing before validate 

https://github.com/dakhama-mehdi/AD_OVH/blob/main/Sources/AD_OVH.PS1

**Review by dakhama-mehdi — COMMENTED** [review]
we can filter by OU 
image

**Comment by dakhama-mehdi** [comment]
new version

**Comment by dakhama-mehdi** [comment]
I'm trying to respect same order and color , with same adjust and news feature

this is other version for server web 
image

**Comment by baardhermansen** [comment]
@dakhama-mehdi You seem to have opened a PR from the wrong repository (and branch). 
image

**Comment by dakhama-mehdi** [comment]
you have reason, i sent a message to create a new repository, i dont know if i have permission, i will try

**Comment by baardhermansen** [comment]
> you have reason, i sent a message to create a new repository, i dont know if i have permission, i will try

Since you have forked this code into your repository, you make changes on the code in your fork, and then submit a pull request from your repository into the master branch in this repository.

**Comment by bwya77** [comment]
merged

**Pull request merged**
